//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenorPezPrincipal.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cargo", Namespace="http://schemas.datacontract.org/2004/07/SenorPezServicio")]
    [System.SerializableAttribute()]
    public partial class Cargo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int dtFechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iAccesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iCodCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iCodEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNombreCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bActivo {
            get {
                return this.bActivoField;
            }
            set {
                if ((this.bActivoField.Equals(value) != true)) {
                    this.bActivoField = value;
                    this.RaisePropertyChanged("bActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int dtFechaRegistro {
            get {
                return this.dtFechaRegistroField;
            }
            set {
                if ((this.dtFechaRegistroField.Equals(value) != true)) {
                    this.dtFechaRegistroField = value;
                    this.RaisePropertyChanged("dtFechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iAcceso {
            get {
                return this.iAccesoField;
            }
            set {
                if ((this.iAccesoField.Equals(value) != true)) {
                    this.iAccesoField = value;
                    this.RaisePropertyChanged("iAcceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iCodCargo {
            get {
                return this.iCodCargoField;
            }
            set {
                if ((this.iCodCargoField.Equals(value) != true)) {
                    this.iCodCargoField = value;
                    this.RaisePropertyChanged("iCodCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iCodEmpleado {
            get {
                return this.iCodEmpleadoField;
            }
            set {
                if ((this.iCodEmpleadoField.Equals(value) != true)) {
                    this.iCodEmpleadoField = value;
                    this.RaisePropertyChanged("iCodEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNombreCargo {
            get {
                return this.vNombreCargoField;
            }
            set {
                if ((object.ReferenceEquals(this.vNombreCargoField, value) != true)) {
                    this.vNombreCargoField = value;
                    this.RaisePropertyChanged("vNombreCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vPassword {
            get {
                return this.vPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.vPasswordField, value) != true)) {
                    this.vPasswordField = value;
                    this.RaisePropertyChanged("vPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        int Login(SenorPezPrincipal.ServiceReference1.Cargo _Obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SenorPezPrincipal.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SenorPezPrincipal.ServiceReference1.IService1>, SenorPezPrincipal.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Login(SenorPezPrincipal.ServiceReference1.Cargo _Obj) {
            return base.Channel.Login(_Obj);
        }
    }
}
