//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenorPezPrincipal.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CARGO", Namespace="http://schemas.datacontract.org/2004/07/SenorPezServicio")]
    [System.SerializableAttribute()]
    public partial class CARGO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dtFechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iAccesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iCodCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iCodEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iCodEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iCodPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vDireccionEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vLogoEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNombreCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNombreEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vRucEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vTelefonoEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bActivo {
            get {
                return this.bActivoField;
            }
            set {
                if ((this.bActivoField.Equals(value) != true)) {
                    this.bActivoField = value;
                    this.RaisePropertyChanged("bActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dtFechaRegistro {
            get {
                return this.dtFechaRegistroField;
            }
            set {
                if ((this.dtFechaRegistroField.Equals(value) != true)) {
                    this.dtFechaRegistroField = value;
                    this.RaisePropertyChanged("dtFechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iAcceso {
            get {
                return this.iAccesoField;
            }
            set {
                if ((this.iAccesoField.Equals(value) != true)) {
                    this.iAccesoField = value;
                    this.RaisePropertyChanged("iAcceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iCodCargo {
            get {
                return this.iCodCargoField;
            }
            set {
                if ((this.iCodCargoField.Equals(value) != true)) {
                    this.iCodCargoField = value;
                    this.RaisePropertyChanged("iCodCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iCodEmpleado {
            get {
                return this.iCodEmpleadoField;
            }
            set {
                if ((this.iCodEmpleadoField.Equals(value) != true)) {
                    this.iCodEmpleadoField = value;
                    this.RaisePropertyChanged("iCodEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iCodEmpresa {
            get {
                return this.iCodEmpresaField;
            }
            set {
                if ((this.iCodEmpresaField.Equals(value) != true)) {
                    this.iCodEmpresaField = value;
                    this.RaisePropertyChanged("iCodEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iCodPerfil {
            get {
                return this.iCodPerfilField;
            }
            set {
                if ((this.iCodPerfilField.Equals(value) != true)) {
                    this.iCodPerfilField = value;
                    this.RaisePropertyChanged("iCodPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vDireccionEmpresa {
            get {
                return this.vDireccionEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.vDireccionEmpresaField, value) != true)) {
                    this.vDireccionEmpresaField = value;
                    this.RaisePropertyChanged("vDireccionEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vLogoEmpresa {
            get {
                return this.vLogoEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.vLogoEmpresaField, value) != true)) {
                    this.vLogoEmpresaField = value;
                    this.RaisePropertyChanged("vLogoEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNombreCargo {
            get {
                return this.vNombreCargoField;
            }
            set {
                if ((object.ReferenceEquals(this.vNombreCargoField, value) != true)) {
                    this.vNombreCargoField = value;
                    this.RaisePropertyChanged("vNombreCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNombreEmpresa {
            get {
                return this.vNombreEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.vNombreEmpresaField, value) != true)) {
                    this.vNombreEmpresaField = value;
                    this.RaisePropertyChanged("vNombreEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vPassword {
            get {
                return this.vPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.vPasswordField, value) != true)) {
                    this.vPasswordField = value;
                    this.RaisePropertyChanged("vPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vRucEmpresa {
            get {
                return this.vRucEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.vRucEmpresaField, value) != true)) {
                    this.vRucEmpresaField = value;
                    this.RaisePropertyChanged("vRucEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vTelefonoEmpresa {
            get {
                return this.vTelefonoEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.vTelefonoEmpresaField, value) != true)) {
                    this.vTelefonoEmpresaField = value;
                    this.RaisePropertyChanged("vTelefonoEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vUsuario {
            get {
                return this.vUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.vUsuarioField, value) != true)) {
                    this.vUsuarioField = value;
                    this.RaisePropertyChanged("vUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BE_INFO", Namespace="http://schemas.datacontract.org/2004/07/SenorPezServicio.DataMember")]
    [System.SerializableAttribute()]
    public partial class BE_INFO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iCodEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal iTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iCodEmpresa {
            get {
                return this.iCodEmpresaField;
            }
            set {
                if ((this.iCodEmpresaField.Equals(value) != true)) {
                    this.iCodEmpresaField = value;
                    this.RaisePropertyChanged("iCodEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal iTotal {
            get {
                return this.iTotalField;
            }
            set {
                if ((this.iTotalField.Equals(value) != true)) {
                    this.iTotalField = value;
                    this.RaisePropertyChanged("iTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        SenorPezPrincipal.ServiceReference1.CARGO Login(SenorPezPrincipal.ServiceReference1.CARGO _Obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GET_INFO", ReplyAction="http://tempuri.org/IService1/GET_INFOResponse")]
        SenorPezPrincipal.ServiceReference1.BE_INFO GET_INFO(SenorPezPrincipal.ServiceReference1.BE_INFO _Obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SenorPezPrincipal.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SenorPezPrincipal.ServiceReference1.IService1>, SenorPezPrincipal.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SenorPezPrincipal.ServiceReference1.CARGO Login(SenorPezPrincipal.ServiceReference1.CARGO _Obj) {
            return base.Channel.Login(_Obj);
        }
        
        public SenorPezPrincipal.ServiceReference1.BE_INFO GET_INFO(SenorPezPrincipal.ServiceReference1.BE_INFO _Obj) {
            return base.Channel.GET_INFO(_Obj);
        }
    }
}
