USE MASTER
GO
IF EXISTS(SELECT * FROM DBO.SYSDATABASES WHERE NAME = 'BD_PEZ') 
BEGIN
    USE MASTER 
	DROP DATABASE BD_PEZ 
END
GO
CREATE DATABASE BD_PEZ;
GO
USE BD_PEZ
GO
IF OBJECT_ID('DECRYPTED_TEXT') IS NOT NULL
BEGIN
	DROP FUNCTION DECRYPTED_TEXT;
END
GO
CREATE FUNCTION DECRYPTED_TEXT 
(@Text varbinary(MAX))
RETURNS VARCHAR(MAX)
AS BEGIN
    DECLARE @RetrunText VARCHAR(MAX)	
    DECLARE @Constant VARCHAR(MAX) = 'M@tSo5T'
    SET @RetrunText = convert(varchar(100),DecryptByPassPhrase(@Constant,LTRIM(RTRIM(@Text))))
    RETURN @RetrunText
END
GO
IF OBJECT_ID('ENCRYPTED_TEXT') IS NOT NULL
BEGIN
	DROP FUNCTION ENCRYPTED_TEXT;
END
GO
CREATE FUNCTION ENCRYPTED_TEXT 
(@Text VARCHAR(MAX))
RETURNS VARBINARY(MAX)
AS BEGIN
    DECLARE @Constant VARCHAR(MAX) = 'M@tSo5T'
    DECLARE @Encry VARBINARY(MAX) 
	SET @Encry = EncryptByPassPhrase(@Constant,  LTRIM(RTRIM(@Text)))
    RETURN @Encry
END
GO
IF OBJECT_ID('MAE_EMPRESA') IS NOT NULL
BEGIN
	DROP TABLE MAE_EMPRESA;
END
GO
CREATE TABLE MAE_EMPRESA
(
	iCodEmpresa INTEGER PRIMARY KEY IDENTITY(1,1),
	vNombreEmpresa VARCHAR(150),
	vLogoEmpresa VARCHAR(MAX),
	vTelefonoEmpresa VARCHAR(15),
	vDireccionEmpresa VARCHAR(100),
	vRucEmpresa VARCHAR(11),
	vDniRepresentante VARCHAR(10),
	cEstado CHAR(1) DEFAULT ('1'),
	bActivo BIT DEFAULT 1
)
GO
IF OBJECT_ID('MAE_PERFILES') IS NOT NULL
BEGIN
	DROP TABLE MAE_PERFILES;
END
GO
CREATE TABLE MAE_PERFILES
(
	iCodPerfiles	INTEGER PRIMARY KEY IDENTITY(1,1),
	vNombrePerfil	VARCHAR(200),
	bActivo			BIT DEFAULT 1
)

/*MAE_PERSONA*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'MAE_PERSONA')
BEGIN
      DROP TABLE MAE_PERSONA
END

CREATE TABLE MAE_PERSONA
(
iCodPersona INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
vNombre VARCHAR (50) NOT NULL,
vApellido VARCHAR(50) NULL,
dtFechaNacimiento DATETIME NULL,
vTelefono VARCHAR(15) NULL,
vMail VARCHAR(100) NULL,
vDireccion VARCHAR(100) NULL,
vDocPersona VARCHAR(8) NULL UNIQUE,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE MAE_PERSONA'
GO

/*MAE_PRESENTACION*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'MAE_PRESENTACION')
BEGIN
      DROP TABLE MAE_PRESENTACION
END

CREATE TABLE MAE_PRESENTACION
(
iCodPresentacion INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
vNombrePresentacion VARCHAR(50) NOT NULL,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE MAE_PRESENTACION'
GO
  
/*MAE_PRODUCTO*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'MAE_PRODUCTO')
BEGIN
      DROP TABLE MAE_PRODUCTO
END

CREATE TABLE MAE_PRODUCTO
(
iCodProducto INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
vNombreProducto VARCHAR NOT NULL UNIQUE,
iCodPresentacion INTEGER REFERENCES MAE_PRESENTACION,
nPrecio NUMERIC(7,2) NOT NULL,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE MAE_PRODUCTO'
GO

/*MAE_PROVEEDOR*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'MAE_PROVEEDOR')
BEGIN
      DROP TABLE MAE_PROVEEDOR
END

CREATE TABLE MAE_PROVEEDOR
(
iCodProveedor INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
vRUC VARCHAR(11) NOT NULL UNIQUE,
vDireccion VARCHAR(100) NOT NULL,
vTelefono VARCHAR (15) NULL,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE MAE_PROVEEDOR'
GO

/*MAE_CARGO*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'MAE_CARGO')
BEGIN
      DROP TABLE MAE_CARGO
END

CREATE TABLE MAE_CARGO
(
iCodCargo INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
vNombreCargo VARCHAR(200) NOT NULL,
iAcceso INTEGER NOT NULL,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE MAE_CARGO'
GO

/*CLIENTE*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'CLIENTE')
BEGIN
      DROP TABLE CLIENTE
END

CREATE TABLE CLIENTE
(
iCodCliente INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
iCodPersona INTEGER NOT NULL REFERENCES MAE_PERSONA,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE CLIENTE'
GO

/*EMPLEADO*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'EMPLEADO')
BEGIN
      DROP TABLE EMPLEADO
END

CREATE TABLE EMPLEADO
(
iCodEmpleado INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
iCodPersona INTEGER NOT NULL REFERENCES MAE_PERSONA,
iCodCargo INTEGER NOT NULL REFERENCES MAE_CARGO,
iCodEmpresa INTEGER NOT NULL  REFERENCES MAE_EMPRESA,
vUsuario VARCHAR(200) NOT NULL,
vPassword VARBINARY(200) NOT NULL, 
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE EMPLEADO'
GO

/*VENTA*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'VENTA')
BEGIN
      DROP TABLE VENTA
END

CREATE TABLE VENTA
(
iCodVenta INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
dtFechaVenta DATETIME NOT NULL,
iCodEmpleadoTrabajador INTEGER NOT NULL REFERENCES EMPLEADO,
iCodCliente INTEGER NOT NULL REFERENCES CLIENTE,
iTipoVenta INTEGER NOT NULL,
iIGV INTEGER NOT NULL,
nTotalVenta NUMERIC(7,2) NOT NULL,
bDescuento BIT NOT NULL,
bDescuentoCantidad BIT NOT NULL,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE VENTA'
GO

/*VENTA_DETALLE*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'VENTA_DETALLE')
BEGIN
      DROP TABLE VENTA_DETALLE
END

CREATE TABLE VENTA_DETALLE
(
iCodVentaDetalle INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
iCodVenta INTEGER NOT NULL REFERENCES VENTA,
iCodProducto INTEGER NOT NULL REFERENCES MAE_PRODUCTO,
iCantidad INTEGER NOT NULL,
nPrecio NUMERIC(7,2) NOT NULL,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE VENTA_DETALLE'
GO

/*COMPRA*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'COMPRA')
BEGIN
      DROP TABLE COMPRA
END

CREATE TABLE COMPRA
(
iCodCompra INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
iCodEmpleadoTrabajador INTEGER NOT NULL REFERENCES EMPLEADO,
dtFechaCompra DATETIME NOT NULL,
iCodProveedor INTEGER NOT NULL REFERENCES MAE_PROVEEDOR,
iTipoCompra INTEGER NOT NULL,
bDescuento BIT NOT NULL,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE COMPRA'
GO

/*COMPRA_DETALLE*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'COMPRA_DETALLE')
BEGIN
      DROP TABLE COMPRA_DETALLE
END

CREATE TABLE COMPRA_DETALLE
(
iCodDetalleCompra INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
iCodCompra INTEGER NOT NULL REFERENCES COMPRA,
iCodProducto INTEGER NOT NULL REFERENCES MAE_PRODUCTO,
iCantidad INTEGER NOT NULL,
nPrecio NUMERIC(7,2) NOT NULL,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE COMPRA_DETALLE'
GO
/*COMPRA_DETALLE*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'PERFIL_USUARIO')
BEGIN
      DROP TABLE PERFIL_USUARIO
END
GO
CREATE TABLE PERFIL_USUARIO
(
iCodPerfilUsuario	INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
iCodPerfil INTEGER NOT NULL REFERENCES MAE_PERFILES,
iCodCargo INTEGER NOT NULL REFERENCES [dbo].[MAE_CARGO],
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE PERFIL_USUARIO'
GO
----------------------------------------
PRINT 'INSERT DATA'
INSERT INTO MAE_EMPRESA (vNombreEmpresa,vLogoEmpresa,vTelefonoEmpresa,vDireccionEmpresa,vRucEmpresa,vDniRepresentante) 
				 VALUES ('SEÑOR PEZ','https://pbs.twimg.com/profile_images/378800000572205704/408f328d9043d58807ed54e162380aaf.png','(01) 5790849','Av. Proceres de la independencia N°1726 - 2do Piso San Juan De Lurigancho, Lima, Peru' ,'20549787313','70423178')

INSERT INTO MAE_PERFILES (vNombrePerfil) VALUES( 'NO' )
INSERT INTO MAE_PERFILES (vNombrePerfil) VALUES( 'PARCIAL' )
INSERT INTO MAE_PERFILES (vNombrePerfil) VALUES( 'TOTAL' ) 

INSERT INTO [dbo].[MAE_PERSONA]([vNombre],[vApellido],[dtFechaNacimiento],[vTelefono],[vMail],[vDireccion],[vDocPersona],[iCodEmpleado],[dtFechaRegistro],[bActivo])
     VALUES('JERAL N.','BENITES GONZALES','1994-11-04 00:00:00','999900948','JeralBenites@gmail.com','luriwashintown','48610078',777,GETDATE(),1)
INSERT INTO [dbo].[MAE_PERSONA]([vNombre],[vApellido],[dtFechaNacimiento],[vTelefono],[vMail],[vDireccion],[vDocPersona],[iCodEmpleado],[dtFechaRegistro],[bActivo])
     VALUES('JAZHIEL N.','BENITES GONZALES','1992-25-11 00:00:00','999900180','Jazhielbg@gmail.com','luriwashintown','47753860',888,GETDATE(),1)

INSERT INTO [dbo].[MAE_CARGO](vNombreCargo,iAcceso,iCodEmpleado)
	VALUES ('ADMIN1',1,777)
INSERT INTO [dbo].[EMPLEADO](iCodPersona,iCodCargo,vUsuario,vPassword,iCodEmpresa)
	VALUES(1,1,'JERAL',DBO.ENCRYPTED_TEXT('JERAL.BENITEZ'),1)
INSERT INTO [dbo].[EMPLEADO](iCodPersona,iCodCargo,vUsuario,vPassword,iCodEmpresa)
	VALUES(2,1,'JAZHIEL',DBO.ENCRYPTED_TEXT('JAZHIEL.BENITEZ'),1)

INSERT INTO PERFIL_USUARIO (iCodPerfil,iCodCargo)VALUES(3,1)
--------------------------------------------
PRINT 'PROCEDURE'
IF OBJECT_ID('[dbo].[SP_LOGIN]') IS NOT NULL
BEGIN
	DROP PROCEDURE [dbo].[SP_LOGIN]
END
GO
--[dbo].[SP_LOGIN]
CREATE PROCEDURE [dbo].[SP_LOGIN]
(
	@vUsuario VARCHAR(200) = NULL,
	@vPassword VARCHAR(200)= NULL
)
AS
BEGIN
	SELECT TOP 1 
		 U.iCodPerfil
		,E.iCodEmpleado
		,E.vUsuario
		,DBO.DECRYPTED_TEXT(E.vPassword) 'vPassword'
		,EM.vNombreEmpresa
		,EM.vRucEmpresa
		,EM.vDireccionEmpresa
		,EM.vLogoEmpresa
		,EM.vTelefonoEmpresa
	FROM
	[dbo].[MAE_CARGO] c
	INNER JOIN PERFIL_USUARIO u
	ON U.iCodCargo = C.iCodCargo
	INNER JOIN  [dbo].[EMPLEADO] E
	ON E.iCodCargo = C.iCodCargo
	INNER JOIN [dbo].[MAE_PERSONA] PE
	ON PE.iCodPersona = E.iCodPersona
	INNER JOIN [dbo].[MAE_EMPRESA] EM
	ON EM.iCodEmpresa = E.iCodEmpresa
	WHERE E.vUsuario =RTRIM(LTRIM(@vUsuario))
	AND DBO.DECRYPTED_TEXT(E.vPassword) = RTRIM(LTRIM(@vPassword))
	AND C.bActivo = 1 AND U.bActivo = 1 AND E.bActivo = 1 AND PE.bActivo = 1
	ORDER BY E.iCodEmpleado DESC
END
GO
PRINT 'PROCEDURE [dbo].[SP_LOGIN]' 
--------------------------------------------

EXEC [dbo].[SP_LOGIN] 'ADMIN','JAZHIEL'
--------------------------------------------
--CONSULTAS
--------------------------------------------
/*SELECT 
	EM.iCodEmpleado,
	PER.vNombre + ' ' +PER.vApellido [NombreApellido],
	CAR.vNombreCargo,
	CAR.vPassword
FROM [dbo].[EMPLEADO] EM
INNER JOIN [dbo].[MAE_PERSONA] PER
ON PER.iCodPersona = EM.iCodPersona
INNER JOIN  [dbo].[MAE_CARGO] CAR
ON CAR.iCodCargo = EM.iCodCargo
GO*/


