USE master
GO

IF EXISTS(SELECT * FROM DBO.SYSDATABASES WHERE NAME = 'BDPez') 
BEGIN
    USE MASTER 
	DROP DATABASE BDPez 
END
GO

CREATE DATABASE BDPez;
GO
USE BDPez
GO
IF OBJECT_ID('MAE_PERFILES') IS NOT NULL
BEGIN
	DROP TABLE MAE_PERFILES;
END
GO
CREATE TABLE MAE_PERFILES
(
	iCodPerfiles	INTEGER PRIMARY KEY IDENTITY(1,1),
	vNombrePerfil	VARCHAR(200),
	bActivo			BIT DEFAULT 1
)

/*MAE_PERSONA*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'MAE_PERSONA')
BEGIN
      DROP TABLE MAE_PERSONA
END

CREATE TABLE MAE_PERSONA
(
iCodPersona INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
vNombre VARCHAR (50) NOT NULL,
vApellido VARCHAR(50) NULL,
dtFechaNacimiento DATETIME NULL,
vTelefono VARCHAR(15) NULL,
vMail VARCHAR(100) NULL,
vDireccion VARCHAR(100) NULL,
vDocPersona VARCHAR(8) NULL UNIQUE,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE MAE_PERSONA'
GO

/*MAE_PRESENTACION*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'MAE_PRESENTACION')
BEGIN
      DROP TABLE MAE_PRESENTACION
END

CREATE TABLE MAE_PRESENTACION
(
iCodPresentacion INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
vNombrePresentacion VARCHAR(50) NOT NULL,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE MAE_PRESENTACION'
GO
  
/*MAE_PRODUCTO*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'MAE_PRODUCTO')
BEGIN
      DROP TABLE MAE_PRODUCTO
END

CREATE TABLE MAE_PRODUCTO
(
iCodProducto INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
vNombreProducto VARCHAR NOT NULL UNIQUE,
iCodPresentacion INTEGER REFERENCES MAE_PRESENTACION,
nPrecio NUMERIC(7,2) NOT NULL,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE MAE_PRODUCTO'
GO

/*MAE_PROVEEDOR*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'MAE_PROVEEDOR')
BEGIN
      DROP TABLE MAE_PROVEEDOR
END

CREATE TABLE MAE_PROVEEDOR
(
iCodProveedor INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
vRUC VARCHAR(11) NOT NULL UNIQUE,
vDireccion VARCHAR(100) NOT NULL,
vTelefono VARCHAR (15) NULL,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE MAE_PROVEEDOR'
GO

/*MAE_CARGO*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'MAE_CARGO')
BEGIN
      DROP TABLE MAE_CARGO
END

CREATE TABLE MAE_CARGO
(
iCodCargo INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
vNombreCargo VARCHAR(200) NOT NULL,
iAcceso INTEGER NOT NULL,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE MAE_CARGO'
GO

/*CLIENTE*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'CLIENTE')
BEGIN
      DROP TABLE CLIENTE
END

CREATE TABLE CLIENTE
(
iCodCliente INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
iCodPersona INTEGER NOT NULL REFERENCES MAE_PERSONA,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE CLIENTE'
GO

/*EMPLEADO*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'EMPLEADO')
BEGIN
      DROP TABLE EMPLEADO
END

CREATE TABLE EMPLEADO
(
iCodEmpleado INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
iCodPersona INTEGER NOT NULL REFERENCES MAE_PERSONA,
iCodCargo INTEGER NOT NULL REFERENCES MAE_CARGO,
vUsuario VARCHAR(200) NOT NULL,
vPassword VARCHAR(200) NOT NULL, 
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE EMPLEADO'
GO

/*VENTA*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'VENTA')
BEGIN
      DROP TABLE VENTA
END

CREATE TABLE VENTA
(
iCodVenta INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
dtFechaVenta DATETIME NOT NULL,
iCodEmpleadoTrabajador INTEGER NOT NULL REFERENCES EMPLEADO,
iCodCliente INTEGER NOT NULL REFERENCES CLIENTE,
iTipoVenta INTEGER NOT NULL,
iIGV INTEGER NOT NULL,
nTotalVenta NUMERIC(7,2) NOT NULL,
bDescuento BIT NOT NULL,
bDescuentoCantidad BIT NOT NULL,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE VENTA'
GO

/*VENTA_DETALLE*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'VENTA_DETALLE')
BEGIN
      DROP TABLE VENTA_DETALLE
END

CREATE TABLE VENTA_DETALLE
(
iCodVentaDetalle INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
iCodVenta INTEGER NOT NULL REFERENCES VENTA,
iCodProducto INTEGER NOT NULL REFERENCES MAE_PRODUCTO,
iCantidad INTEGER NOT NULL,
nPrecio NUMERIC(7,2) NOT NULL,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE VENTA_DETALLE'
GO

/*COMPRA*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'COMPRA')
BEGIN
      DROP TABLE COMPRA
END

CREATE TABLE COMPRA
(
iCodCompra INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
iCodEmpleadoTrabajador INTEGER NOT NULL REFERENCES EMPLEADO,
dtFechaCompra DATETIME NOT NULL,
iCodProveedor INTEGER NOT NULL REFERENCES MAE_PROVEEDOR,
iTipoCompra INTEGER NOT NULL,
bDescuento BIT NOT NULL,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE COMPRA'
GO

/*COMPRA_DETALLE*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'COMPRA_DETALLE')
BEGIN
      DROP TABLE COMPRA_DETALLE
END

CREATE TABLE COMPRA_DETALLE
(
iCodDetalleCompra INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
iCodCompra INTEGER NOT NULL REFERENCES COMPRA,
iCodProducto INTEGER NOT NULL REFERENCES MAE_PRODUCTO,
iCantidad INTEGER NOT NULL,
nPrecio NUMERIC(7,2) NOT NULL,
iCodEmpleado INTEGER NOT NULL,
dtFechaRegistro DATETIME DEFAULT GETDATE(),
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE COMPRA_DETALLE'
GO
/*COMPRA_DETALLE*/
IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'PERFIL_USUARIO')
BEGIN
      DROP TABLE PERFIL_USUARIO
END
GO
CREATE TABLE PERFIL_USUARIO
(
iCodPerfilUsuario	INTEGER NOT NULL PRIMARY KEY IDENTITY (1,1),
iCodPerfil INTEGER NOT NULL REFERENCES MAE_PERFILES,
iCodCargo INTEGER NOT NULL REFERENCES [dbo].[MAE_CARGO],
bActivo BIT DEFAULT 1
)
GO

PRINT 'TABLE PERFIL_USUARIO'
GO
----------------------------------------
PRINT 'INSERT DATA'

INSERT INTO MAE_PERFILES (vNombrePerfil) VALUES( 'NO' )
INSERT INTO MAE_PERFILES (vNombrePerfil) VALUES( 'PARCIAL' )
INSERT INTO MAE_PERFILES (vNombrePerfil) VALUES( 'TOTAL' ) 

INSERT INTO [dbo].[MAE_PERSONA]([vNombre],[vApellido],[dtFechaNacimiento],[vTelefono],[vMail],[vDireccion],[vDocPersona],[iCodEmpleado],[dtFechaRegistro],[bActivo])
     VALUES('JERAL N.','BENITES GONZALES','1994-11-04 00:00:00','999900948','JeralBenites@gmail.com','luriwashintown','48610078',777,GETDATE(),1)
INSERT INTO [dbo].[MAE_PERSONA]([vNombre],[vApellido],[dtFechaNacimiento],[vTelefono],[vMail],[vDireccion],[vDocPersona],[iCodEmpleado],[dtFechaRegistro],[bActivo])
     VALUES('JAZHIEL N.','BENITES GONZALES','1992-25-11 00:00:00','999900180','Jazhielbg@gmail.com','luriwashintown','47753860',888,GETDATE(),1)

INSERT INTO [dbo].[MAE_CARGO](vNombreCargo,iAcceso,iCodEmpleado)
	VALUES ('ADMIN1',1,777)

INSERT INTO [dbo].[EMPLEADO](iCodPersona,iCodCargo,vUsuario,vPassword)
	VALUES(1,1,'ADMIN','JERAL')
INSERT INTO [dbo].[EMPLEADO](iCodPersona,iCodCargo,vUsuario,vPassword)
	VALUES(2,1,'ADMIN','JAZHIEL')

INSERT INTO PERFIL_USUARIO (iCodPerfil,iCodCargo)VALUES(3,1)
--------------------------------------------
PRINT 'PROCEDURE'
IF OBJECT_ID('[dbo].[SP_LOGIN]') IS NOT NULL
BEGIN
	DROP PROCEDURE [dbo].[SP_LOGIN]
END
GO
--[dbo].[SP_LOGIN]
CREATE PROCEDURE [dbo].[SP_LOGIN]
(
	@vUsuario VARCHAR(200) = NULL,
	@vPassword VARCHAR(200)= NULL
)
AS
BEGIN
	SELECT 		 
		 U.iCodPerfil
		,E.iCodEmpleado
		,E.vUsuario
		,E.vPassword
	FROM
	[dbo].[MAE_CARGO] c
	INNER JOIN PERFIL_USUARIO u
	ON U.iCodCargo = C.iCodCargo
	INNER JOIN  [dbo].[EMPLEADO] E
	ON E.iCodCargo = C.iCodCargo
	INNER JOIN [dbo].[MAE_PERSONA] PE
	ON PE.iCodPersona = E.iCodPersona
	WHERE vNombreCargo =ISNULL(RTRIM(LTRIM(@vUsuario)),vNombreCargo)
	AND  vPassword = ISNULL(RTRIM(LTRIM(@vPassword)),vPassword)
	AND C.bActivo = 1 AND U.bActivo = 1 AND E.bActivo = 1 AND PE.bActivo = 1
END
GO
PRINT 'PROCEDURE [dbo].[SP_LOGIN]' 
--------------------------------------------

EXEC [dbo].[SP_LOGIN] 'ADMIN1','JAZHIEL'
--------------------------------------------
--CONSULTAS
--------------------------------------------
/*SELECT 
	EM.iCodEmpleado,
	PER.vNombre + ' ' +PER.vApellido [NombreApellido],
	CAR.vNombreCargo,
	CAR.vPassword
FROM [dbo].[EMPLEADO] EM
INNER JOIN [dbo].[MAE_PERSONA] PER
ON PER.iCodPersona = EM.iCodPersona
INNER JOIN  [dbo].[MAE_CARGO] CAR
ON CAR.iCodCargo = EM.iCodCargo
GO*/


